#! /bin/sh

echo "Setting up Traefik...."

helm repo add traefik https://traefik.github.io/charts
helm repo update

helm upgrade --install traefik traefik/traefik -n kube-system -f "$(dirname -- "$0")/configs/values.yaml"

kubectl apply -f "$(dirname -- "$0")/configs/middleware.yaml"
kubectl apply -f "$(dirname -- "$0")/configs/dashboard.yaml"
