kubeProxyReplacement: true
k8sServiceHost: 192.168.68.1
k8sServicePort: 6443
hostServices:
  enabled: false
nodePort:
  enabled: true
l2announcements:
  enabled: true
externalIPs:
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
rollOutCiliumPods: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      lbipam.cilium.io/ips: 192.168.68.69
gatewayAPI:
  enabled: true
prometheus:
  enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    enableOpenMetrics: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      hosts:
      - hubble.homelab