kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.homelab
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd

  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-longhorn-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn
          resources:
            requests:
              storage: 5Gi

grafana:
  plugins:
    - grafana-piechart-panel
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana.homelab
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd
  grafana.ini:
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth.basic:
      enabled: false

  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection
