apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ui
  namespace: gitea
spec:
  rules:
    - host: gitea.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  entryPoints:
    - ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: gitea-ssh
          port: 22
          # nativeLB: true
  # tls:
  #   passthrough: true
