#! /bin/sh

echo "Setting up Cilium..."

helm repo add cilium https://helm.cilium.io
helm repo update

helm install cilium cilium/cilium \
    --create-namespace -n kube-system \
    -f "$(dirname -- "$0")/configs/values.yaml"

sleep 10

echo "Setting up the IP pool"
kubectl apply -f "$(dirname -- "$0")/configs/crds.yaml"