defaultSettings:
  defaultReplicaCount: 2
  nodeDrainPolicy: "always-allow"
persistence:
  defaultClassReplicaCount: 2
serviceMonitor:
  enabled: true
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 2
  snapshotterReplicaCount: 2
longhornUI:
  replicas: 1
ingress:
  enabled: true
  host: longhorn.homelab
  pathType: Prefix
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd