apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-whitelist
  namespace: default
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.1/32
    ipStrategy:
      excludedIPs: []
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: default
spec:
  basicAuth:
    secret: basic-auth-secret
---
# htpasswd -nb user password | openssl base64
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: default
data:
  users: |2
    YWRtaW46JGFwcjEkUmhSZmtmOHckdjF6SmFHYS9BTnNwLlpsLzBVZk1YMQoK
