additionalArguments:
  - "--api"
  - "--api.dashboard=true"
  - "--api.insecure=true"
providers:
  kubernetesCRD:
    allowCrossNamespace: true
metrics:
  prometheus:
    service:
      enabled: true
logs:
  access:
    enabled: true
ports:
  ssh:
    port: 2222
    expose: 
      default: true
    exposedPort: 22
  dns:
    port: 5353
    expose: 
      default: true
    exposedPort: 53
    protocol: TCP
  dns-udp:
    port: 5353
    expose: 
      default: true
    exposedPort: 53
    protocol: UDP
service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.68.69
