#! /bin/sh

echo "Setting up Longhorn..."

helm repo add longhorn https://charts.longhorn.io
helm repo update

helm install longhorn longhorn/longhorn \
    --create-namespace -n longhorn \
    -f "$(dirname -- "$0")/configs/values.yaml"

kubectl apply -f "$(dirname -- "$0")/configs/ingress.yaml"