#! /bin/sh

kubectl create namespace docker
kubectl apply -f "$(dirname -- "$0")/configs/manifest.yaml"

kubectl exec -it dockerd-statefulset-0 -n docker -- passwd

ssh-copy-id root@192.168.68.69

docker context create --docker host=ssh://root@192.168.68.69 homelab
docker context use homelab