#! /bin/sh

kubectl create namespace docker
kubectl apply -f "$(dirname -- "$0")/configs/manifest.yaml"

sleep 60

kubectl exec -it dockerd-statefulset-0 -n docker -- passwd

ssh-copy-id root@192.168.1.88

docker context create --docker host=ssh://root@192.168.1.88 homelab
docker context use homelab