apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: homelab
spec:
  hosts:
  - ssh:
      address: 192.168.68.1
      user: kai
    role: controller+worker
    installFlags:
    - --disable-components=konnectivity-server,metrics-server,autopilot
    - --no-taints
  - ssh:
      address: 192.168.68.2
      user: kai
    role: controller+worker
    installFlags:
    - --disable-components=konnectivity-server,metrics-server,autopilot
    - --no-taints
  - ssh:
      address: 192.168.68.3
      user: kai
    role: controller+worker
    installFlags:
    - --disable-components=konnectivity-server,metrics-server,autopilot
    - --no-taints
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false