kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.homelab
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd

  prometheusSpec:
    retention: 14d
    enableRemoteWriteReceiver: true
    additionalScrapeConfigs:
      - job_name: "home-router"
        scrape_interval: 10s
        static_configs:
          - targets:
              - "home-router.lan:9100"
              - "home-router.lan:9103"
              - "home-router.lan:9617"
            labels:
              group: "home-router"
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-longhorn-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn
          resources:
            requests:
              storage: 200Gi

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana.homelab
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd
  grafana.ini:
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth.basic:
      enabled: false
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100
      isDefault: false
      jsonData:
        maxLines: 1000
        queryType: logs
  plugins:
    - grafana-piechart-panel
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

alertmanager:
  ingress:
    enabled: true
    hosts:
      - alerts.homelab
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd
